### ISSUE TITLE
Multiple Errors on execution

### ISSUE THREAD

**Issue by Haizanjs** [hannob/optionsbleed#6]
![image](https://user-images.githubusercontent.com/27821536/50373079-4bd40280-05d1-11e9-99c1-1125993e98fa.png)

**Comment by hannob** [comment]
Without further info there's little I can say, looks like some kind of http error.

Can you try snallygaster with
```
snallygaster -t optionsbleed [host]
```
?

https://github.com/hannob/snallygaster

**Comment by Haizanjs** [comment]
I have attempted to use **snallygaster** , installed with pip3 successfully.
